static const char *tag_init_data =
    "## This !tags.m3u is formatted weirdly\n"
    "## in order to test how sloppy the library\n"
    "## can take it\n"
    "\n"
    "#@ALBUM Zumi's GB Music Engine v1\n"
    "#@company Zumi\n"
    "# @Publisher none\n"
    "# @aRTIST Unknown\n"
    "#@date  2015-10-09\n"
    "#@ripper Zumi\n"
    "#@tagger Zumi\n"
    "# @sequencer Zumi\n"
    "# @engineer Zumi\n"
    "#@fade 00:00:10.000\n"
    "\n"
    "# %title Ocean Loader 4\n"
    "# %composer Jonathan Dunn\n"
    "# %comment Just a short snippet.\n"
    "# %length 0:23\n"
    "# %fade 5\n"
    "\n"
    "gbstest.gbs?1\n"
    "\n"
    "#   %track 12\n"
    "# %title Super Pitfall - Overworld\n"
    "# %length 32.000\n"
    "	#	%comment Transcription of the NES version,\n"
    "	#%comment with extras from the PC-88 version.\n"
    "gbstest.gbs?2\n"
    "\n"
    "# %title Pokémon Red & Blue - Intro\n"
    "# %length 00:15.000\n"
    "#%composer Junichi Masuda\n"
    "#	%comment No noise, because I sucked\n"
    "\n"
    "\n"
    "gbstest.gbs?3\n"
    "\n"
    "# %title We Are the Crystal Gems\n"
    "# %length 0:00:54.000\n"
    "# %composer Rebecca Sugar, Aivi & Surasshu\n"
    "gbstest.gbs?6\n";