static const char *tag_init_data =
    "## This !tags.m3u is formatted weirdly\n"
    "## in order to test how sloppy the library\n"
    "## can take it\n"
    "\n"
    "#@ALBUM Zumi's GB Music Engine v1\n"
    "#@company Zumi\n"
    "# @Publisher none\n"
    "# @aRTIST Unknown\n"
    "#@date  2015-10-09\n"
    "#@ripper Zumi\n"
    "#@tagger Zumi\n"
    "# @sequencer Zumi\n"
    "# @engineer Zumi\n"
    "#@fade 00:00:10.000\n"
    "\n"
    "# %title Ocean Loader 4\n"
    "# %composer Jonathan Dunn\n"
    "# %comment Just a short snippet.\n"
    "# %length 0:23\n"
    "# %fade 5\n"
    "\n"
    "gbstest.gbs?1\n"
    "\n"
    "#   %track 12\n"
    "# %title Super Pitfall - Overworld\n"
    "# %length 32.000\n"
    "	#	%comment Transcription of the NES version,\n"
    "	#%comment with extras from the PC-88 version.\n"
    "gbstest.gbs?2\n"
    "\n"
    "# %title Pokémon Red & Blue - Intro\n"
    "# %length 00:15.000\n"
    "#%composer Junichi Masuda\n"
    "#	%comment No noise, because I sucked\n"
    "\n"
    "\n"
    "gbstest.gbs?3\n"
    "\n"
    "# %title We Are the Crystal Gems\n"
    "# %length 0:00:54.000\n"
    "# %composer Rebecca Sugar, Aivi & Surasshu\n"
    "gbstest.gbs?6\n";

static const char *katakis_3d_test =
    "\n"
    "# @album       Katakis 3D\n"
    "# @company     Similis\n"
    "# @artist      Tufan Uysal\n"
    "# @ripper      zlago\n"
    "# @tagger      Zumi, zlago\n"
    "# @date        2001\n"
    "\n"
    "# %title   Katakis (Remix)\n"
    "# %length  3:07\n"
    "# %fade    0:00:10.000\n"
    "# %artist  Chris Huelsbeck, Tufan Uysal\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?1\n"
    "\n"
    "# %title   Loud 'n Proud\n"
    "# %length  0:43\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?2\n"
    "\n"
    "# %title   Flight to Hell\n"
    "# %length  1:08\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?3\n"
    "\n"
    "# %title   The Big Thing\n"
    "# %length  0:39\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?4\n"
    "\n"
    "# %title   Electrical Motions\n"
    "# %length  1:21\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?5\n"
    "\n"
    "# %title   Protected Beat\n"
    "# %length  0:19\n"
    "# %fade    5\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?6\n"
    "\n"
    "# %title   Secret Cycles\n"
    "# %length  1:52\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?7\n"
    "\n"
    "# %title   Radioactive Attack\n"
    "# %length  0:32\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?8\n"
    "\n"
    "# %title   Enforcer\n"
    "# %length  1:20\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?9\n"
    "\n"
    "# %title   Someone Wanna Party\n"
    "# %length  0:40\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?10\n"
    "\n"
    "# %title   Rasit's Spiritual Dreams\n"
    "# %length  1:08\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?11\n"
    "\n"
    "# %title   Oriental Danger\n"
    "# %length  0:40\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?12\n"
    "\n"
    "# %title   Boomin' Back Katakis\n"
    "# %length  3:51\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?13\n"
    "\n"
    "# %title   Master of Universe\n"
    "# %length  1:04\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?14\n"
    "\n"
    "# %title   The Impregnable\n"
    "# %length  0:51\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?15\n"
    "\n"
    "# %title   30 Seconds to Go...\n"
    "# %length  0:35\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?16\n"
    "\n"
    "# %title   Beyond the Stars\n"
    "# %length  4:17\n"
    "# %fade    0:00:10.000\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?17\n"
    "\n"
    "# %title   Crush Boom Bang\n"
    "# %length  0:06\n"
    "# %fade    1\n"
    "Katakis 3D (Unreleased)(2001)(Similis)[GBC].gbs?18\n"
    "\n";
